agents:
  - agent_ls
  - agent_dc
  - agent_bat
location: ny
cintensity_file: 'NYIS_NG_&_avgCI.csv'
weather_file: 'USA_NY_New.York-LaGuardia.epw'
workload_file: 'alibaba_spot_gpu_v2026/Alibaba_Spot_GPU_Hourly.csv'
max_bat_cap_Mw: 1.0
individual_reward_weight: 0.8
flexible_load: 0.6
ls_reward: default_ls_reward
dc_reward: default_dc_reward
bat_reward: default_bat_reward
dc_config_file: 'dc_config.json'
month: 6
days_per_episode: 7
partial_obs: True
nonoverlapping_shared_obs_space: True